name: ecspresso
on:
  workflow_dispatch: {}
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: curl -sS https://api.github.com/repos/kayac/ecspresso/releases
      - run: jq --version
      - uses: actions/checkout@v3
      - uses: kayac/ecspresso@v1
        with:
          version: latest
